### ISSUE TITLE
Regression in 4.0.0-beta0003

### ISSUE THREAD

**Issue by sungam3r** [shouldly/shouldly#693] opened 2020-10-13 08:29 UTC
```c#
  int? i = null;
  i.ShouldBeNull(); // OK in 4.0.0-beta0002 but CS0452 in 4.0.0-beta0003 : The type 'int?' must be a reference type in order to use it as parameter 'T' in the generic type or method 'ShouldBeNullExtensions.ShouldBeNull<T>(T?, string?)'	
  i.ShouldBe(null); // OK in both 4.0.0-beta0002 and 4.0.0-beta0003
```

**Comment by Shane32** [comment] 2020-10-13 13:59
Duplicate of #674 ?

**Comment by sungam3r** [comment] 2020-10-13 14:18
Maybe. I remember that error, but clearly speaking I was too lazy to look for it.

**Comment by SimonCropp** [comment] 2020-10-15 21:48
@JosephWoodward can u deploy 4.0.0-beta0004. i tried but got an error

**Comment by JosephWoodward** [comment] 2020-10-15 22:20
@SimonCropp Sure, I'll try it in a mo. What error were you seeing?

**Comment by SimonCropp** [comment] 2020-10-15 22:22
![image](https://user-images.githubusercontent.com/122666/96192074-01cfc400-0f91-11eb-831b-3fd3fab05fa9.png)

**Comment by JosephWoodward** [comment] 2020-10-16 08:56
@SimonCropp @Shane32 @sungam3r There we go, that's been deployed and can be found [here](https://www.nuget.org/packages/Shouldly/4.0.0-beta.4)

**Comment by JosephWoodward** [comment] 2020-10-16 16:18
I'm going to close this issue off now the package is available, please feel free to reopen if necessary.

**Closed by JosephWoodward** 2020-10-16 16:18 UTC
