### ISSUE TITLE
bug Should.Throw

### ISSUE THREAD

**Issue by AntoninB** [shouldly/shouldly#198] opened 2015-03-27 11:27 UTC
This works: 
                try
                {
                    methodTested();
                    Assert.Fail("No exception throwned");
                }
                catch (MyException){}
                catch (Exception) { Assert.Fail("Wrong exception called");}

this doesn't in 2.4.0:
                Should.Throw<MyException>(() => methodTested());

**Comment by JakeGinnivan** [comment] 2015-03-27 11:39
Am just trying to understand the issue. It seems fine for me. Here is a simple LinqPad script, failing to replicate this issue.
```
void Main()
{
	try
	{
		try
		{
			methodTested();
			throw new FailedException("No exception throwned");
		}
		catch (MyException){}
		catch (FailedException){ throw; }
		catch (Exception) { throw new FailedException("Wrong exception called");}
	}
	catch (Exception ex)
	{
		ex.Dump("Example with not throwing");
	}
	

	// Example code passing
	try
	{
		throwingMethodTested();
		throw new FailedException("No exception throwned");
	}
	catch (MyException){}
	catch (FailedException){ throw; }
	catch (Exception) { throw new FailedException("Wrong exception called");}
	
	// Shouldly fail sample
	try
	{
		Should.Throw<MyException>(() => methodTested());
	}
	catch (Exception ex)
	{
		ex.Dump("Shouldly with not throwing");
	}
	
	// Shouldly normal
	Should.Throw<MyException>(() => throwingMethodTested());
}

void methodTested() {
}
void throwingMethodTested() {
	throw new MyException();
}

class MyException : Exception { }
class FailedException : Exception {
	public FailedException(string message) : base(message) { }
}
```

The output is:
```
## Example with not throwing
FailedException: No exception throwned 

## Shouldly with not throwing
ChuckedAWobbly: The provided expression throw UserQuery+MyException but does not 
```

Can you elaborate on your issue?

**Comment by JakeGinnivan** [comment] 2015-03-30 07:54
@AntoninB just following up on this

**Comment by AntoninB** [comment] 2015-03-31 09:46
It's a little more complicated to reproduce than I thought: 
Here are five class, in two project

project TestLocalProject, a console project

    public abstract class AbstractClass
    {
        public int intNumerator { get; set; }

        public void TestMethod()
        {
            throw new PersonalizedException("test message", 1);
        }
    }

    public class TestClass:AbstractClass
    {
    }

    public interface IPersonalizedException
    {
        int NumberException { get; set; }
        string ClassMessage { get; }
    }
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;

namespace TestLocalProject
{
    [Serializable]
    public class PersonalizedException : Exception, IPersonalizedException
    {
        public int NumberException { get; set; }

        public string ClassMessage
        {
            get
            {
                return "PersonalizedException class message ";
            }
        }

        public PersonalizedException(string pMessage, int pNumberException)
            : base(pMessage)
        {
            NumberException = pNumberException;
        }

        public PersonalizedException(string pMessage, Exception pException, int pNumberException)
            : base(pMessage, pException)
        {
            NumberException = pNumberException;
        }

        public PersonalizedException(SerializationInfo pSerializationInfo, StreamingContext pStreamingContext, int pNumberException)
            : base(pSerializationInfo, pStreamingContext)
        {
            NumberException = pNumberException;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public override void GetObjectData(SerializationInfo pOInfo, StreamingContext pOContext)
        {
            base.GetObjectData(pOInfo, pOContext);
            pOInfo.AddValue("NumberException", NumberException);
        }
    }
}

Unit test project

    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            TestClass testClass = new TestClass();
            try
            {
                testClass.TestMethod();
                throw new Exception("Should not be there");
            }
            catch (PersonalizedException) { }
            catch (Exception) { throw; }
            Should.Throw<PersonalizedException>(() => { testClass.TestMethod(); });

        }
    }

When I run the unit test, it fails because the Should.Throw doesn't catch the PersonalizedException.

**Comment by JakeGinnivan** [comment] 2015-03-31 10:40
Ok, so what version of .net are you using?

I just put this in linqpad:

``` csharp
void Main()
{
	TestClass testClass = new TestClass();

        Should.Throw<PersonalizedException>(() => { testClass.TestMethod(); });
		
		"works".Dump();
}

[Serializable]
public class PersonalizedException : Exception, IPersonalizedException
{
public int NumberException { get; set; }

    public string ClassMessage
    {
        get
        {
            return "PersonalizedException class message ";
        }
    }

    public PersonalizedException(string pMessage, int pNumberException)
        : base(pMessage)
    {
        NumberException = pNumberException;
    }

    public PersonalizedException(string pMessage, Exception pException, int pNumberException)
        : base(pMessage, pException)
    {
        NumberException = pNumberException;
    }

    public PersonalizedException(SerializationInfo pSerializationInfo, StreamingContext pStreamingContext, int pNumberException)
        : base(pSerializationInfo, pStreamingContext)
    {
        NumberException = pNumberException;
    }

    /// <summary>
    /// 
    /// </summary>
    /// <returns></returns>
    public override void GetObjectData(SerializationInfo pOInfo, StreamingContext pOContext)
    {
        base.GetObjectData(pOInfo, pOContext);
        pOInfo.AddValue("NumberException", NumberException);
    }
}

public abstract class AbstractClass
{
    public int intNumerator { get; set; }

    public void TestMethod()
    {
        throw new PersonalizedException("test message", 1);
    }
}

public class TestClass:AbstractClass
{
}

public interface IPersonalizedException
{
    int NumberException { get; set; }
    string ClassMessage { get; }
}
```

The output is `works`

I can't reproduce :(

**Comment by AntoninB** [comment] 2015-03-31 11:12
Visual C# 2013 update 4

and for the unit test project 
Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll v 10.0.0.0
runtime version v2.0.50727

**Comment by JakeGinnivan** [comment] 2015-03-31 11:36
Are you able to submit a failing test in a pull request?

**Comment by AntoninB** [comment] 2015-03-31 11:37
It's my first time using GitHub. Let me a moment to know how I can do this.

**Comment by JakeGinnivan** [comment] 2015-03-31 11:47
Sure!

https://help.github.com/articles/creating-a-pull-request/ and https://help.github.com/articles/using-pull-requests/ are useful resources. 

As for tools, if you don't have git setup. This is how I do it: http://jake.ginnivan.net/setting-up-git/

Just ask if you have any specific issues

**Comment by AntoninB** [comment] 2015-03-31 12:40
I think it's done. Unfortuantelly I have to work now so I won't be able to do much before I come home in 4/6 hours

**Comment by JakeGinnivan** [comment] 2015-03-31 12:42
No probs, will try to have a look.

**Comment by JakeGinnivan** [comment] 2015-04-06 08:55
This is working fine for me. `Should.Throw<PersonalizedException>(() => { testClass.TestMethod(); });` calls TestMethod which throws a `PersonalizedException`. So the assertion is valid and Shouldly does not throw.

Should.Throw will fail if the exception is *not* thrown. If you want shouldly to fail when an exception *is* thrown you want `Should.NotThrow`

**Comment by JakeGinnivan** [comment] 2015-04-08 18:15
Going to close this. I can't reproduce. Feel free to reopen if you can elaborate on the issue.

**Closed by JakeGinnivan** 2015-04-08 18:15 UTC

**Comment by jimb6** [comment] 2023-01-07 17:57
When I try to test a database table with unique constraints, I run into this problem. Every time I run the unit test, it misses the exception. Always throwing an error.

**Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.** 

Microsoft.EntityFrameworkCore.DbUpdateException
An error occurred while saving the entity changes. See the inner exception for details.

Microsoft.Data.Sqlite.SqliteException
SQLite Error 19: 'UNIQUE constraint failed: TypeCodes.Code, TypeCodes.Name'.

`Should.Throw<DbUpdateException>(async() => { await _unitOfWorkManager.Current.SaveChangesAsync(); });`
