### ISSUE TITLE
ThrowAsync<T> not catching FluentValidation.ValidationException

### ISSUE THREAD

**Issue by daningalla** [shouldly/shouldly#585] opened 2019-10-21 22:26 UTC
My Xunit fact fails here, even though I've verified the exception is a ValidationException.

```
await Should.ThrowAsync<ValidationException>(() =>
    mediator.Send(new Request {ParameterA = -1, ParameterB = 50}));
```

If I wrap this in try/catch, the test will pass. E.g.

```
try
{
    await Should.ThrowAsync<ValidationException>(() =>
        mediator.Send(new Request {ParameterA = -1, ParameterB = 50}));
}
catch (ValidationException ex)
{
  // Debugger breaks here
}
```
using:
Xunit 2.4.0
Shouldly 3.0.2
Netcoreapp 2.2

```
Error Message:
 FluentValidation.ValidationException : Validation failed:
 -- ParameterA: 'Parameter A' must be greater than '-1'.
   at company.Coso.ServiceModel.ValidationBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in C:\Users\me\Dev\company\company.cmp.sandbox\src\corelibs\ServiceModel\company\Coso\ServiceModel\ValidationBehavior.cs:lin
e 47
   at company.Coso.ServiceModel.ValidationBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in C:\Users\me\Dev\company
\company.cmp.sandbox\src\corelibs\ServiceModel\company\Coso\ServiceModel\ValidationBehavior.cs:line 47
   at MediatR.Internal.RequestHandlerWrapperImpl`2.Handle(IRequest`1 request, CancellationToken cancellationToken, ServiceFactory serviceFactory)
   at company.Coso.ServiceModel.ValidationBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in C:\Users\me\Dev\wt
   at company.Coso.ServiceModel.ValidationBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in C:\Users\me\Dev\w
   at company.Coso.ServiceModel.ValidationBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in C:\Users\me\Dev\company\company.cmp.sandbox\src\corelibs\ServiceModel\company\Coso\ServiceModel\ValidationBehavior.cs:line 47
   at MediatR.Internal.RequestHandlerWrapperImpl`2.Handle(IRequest`1 request, CancellationToken cancellationToken, ServiceFactory serviceFactory)
   at MediatR.Mediator.Send[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at company.Coso.ServiceCollectionExtensionTests.<>c__DisplayClass8_0.<AddServiceModel_Adds_Validation_Services>b__0() in C:\Users\me\Dev\company\company.cmp.sandbox\test\corelibs\ServiceModel\company\Coso\ServiceCollectionExtensionTests.cs:line 73
   at Shouldly.Should.ThrowAsync[TException](Func`1 actual, Func`1 customMessage) in C:\projects\shouldly\src\Shouldly\ShouldStaticClasses\ShouldThrowTaskAsync.cs:line 51
   at Shouldly.Should.ThrowAsync[TException](Func`1 actual) in C:\projects\shouldly\src\Shouldly\ShouldStaticClasses\ShouldThrowTaskAsync.cs:line 40
   at company.Coso.ServiceCollectionExtensionTests.AddServiceModel_Adds_Validation_Services() in C:\Users\me\Dev\company\company.cmp.sandbox\test\corelibs\ServiceModel\company\Coso\ServiceCollectionExtensionTests.cs:line 72
--- End of stack trace from previous location where exception was thrown ---

```

I suspect this is something peculiar with FluentValidator since I have a test right above this one that does pass for a different exception type (same mediator pipeline).

Thanks for looking.

**Comment by JosephWoodward** [comment] 2019-10-22 00:25
Thanks for reporting this, I'll take a look and try reproduce it.

**Comment by sungam3r** [comment] 2019-10-22 07:50
It looks like I came across this error using `ThrowAsync.` Try 4.0.0 beta version.

**Comment by daningalla** [comment] 2019-10-22 19:28
@sungam3r  - still throws when using 4.0.0-beta0001

**Comment by sungam3r** [comment] 2019-10-22 20:29
Maybe [4.0.0-beta0002](https://github.com/shouldly/shouldly/pull/560#issuecomment-538362077) ?
#457, #560

**Comment by daningalla** [comment] 2019-10-22 20:54
Yep - that did it

@sungam3r

**Comment by JosephWoodward** [comment] 2019-10-23 08:15
@daningalla Updating to the 4.0 beta 2 fixed it?

**Comment by SimonCropp** [comment] 2020-07-04 11:29
closing since this is fixed in the current beta.

@daningalla no idea on the next release. perhaps raise a new issue to have that specific discussion?

**Closed by SimonCropp** 2020-07-04 11:29 UTC
