### ISSUE TITLE
First time trying it out and nothing as epxected

### ISSUE THREAD

**Issue by ppumkin** [shouldly/shouldly#533] opened 2018-10-16 08:11 UTC
I have no idea why the output is like this? Cant really make heads or tails...

![image](https://user-images.githubusercontent.com/1249683/47001872-66968080-d123-11e8-8790-afdc23b6adea.png)

What does it mean build my test project with full debug information? It is already in debug and it was built.

What are all the hieroglyphics about?

**Comment by ppumkin** [comment] 2018-10-17 08:33
Oh OK- Seems like I found this plugin in a bad time.  😮 

PS - I was watching https://www.youtube.com/watch?v=7POV7JjpHrs&t=1543s  (Microsoft Visual Studio - Building High Performance Extensions (Part 1)) while learning how to build extensions.

Can't wait till the fix comes in.. will be converting everything to Shouldly 😄

**Comment by JosephWoodward** [comment] 2018-10-17 16:12
@ppumkin Out of interest what Target Framework Moniker are you targeting?

**Comment by ppumkin** [comment] 2018-10-18 09:36
Ahh good question because I have mixed frameworks for testing.

I installed Shouldly on a CORE 2.1 project and it actually works OK  with that! ✔️ 

Then I tried in on my integration test on another project .NET 4.6.1 and its OK there. ✔️ 

Actually, I see that the first time I tried it was on a "Subscription Project" which is CORE 2.1 project ❌ 

So it does not seem to be anything with the target framework. 😕 

The command is
`_pol.CompanyDetails.AddressLine3.ShouldBe("12");`  (this is a deliberate error)

Which is a standard DTO Class that is returned by an in memory MongoDB (Mongo2Go)

**Comment by JosephWoodward** [comment] 2018-10-18 10:03
@ppumkin Thanks, would you mind sharing the .csproj you're using on subscription project so I could take  a look? No feel free to strip anything out that's confidential.

**Comment by JosephWoodward** [comment] 2018-10-24 21:52
Been looking into this further and it appears that it works as expected if launched in a console app 🤷‍♂️  cc @stuart-lang

**Comment by JosephWoodward** [comment] 2018-10-24 22:02
As this is a duplicate of https://github.com/shouldly/shouldly/issues/524 I think it's best we close this and focus on 524.

**Closed by JosephWoodward** 2018-10-24 22:02 UTC

**Comment by JosephWoodward** [comment] 2018-11-01 01:52
@ppumkin Found the issue, expect a fix soon!

**Comment by ppumkin** [comment] 2018-11-05 09:33
@JosephWoodward awesome, Is there a PR i can look at. Wouldn't mind having a small nosy 😄

**Comment by JosephWoodward** [comment] 2018-11-05 09:58
@ppumkin There is, though [it's nothing exciting](https://github.com/shouldly/shouldly/commit/5bc553e4d1cbf6e967af7e0a84e7d463c2f880a7). Ultimately because we're releasing Shouldly with optimisations enabled, a lot of method inlining and tail calls are happening making it very difficult to accurately get the original call location. So ultimately the best thing for us to do at this point in time is disable optimisations (being an assertion library, performance isn't a priority).

If you're interested in the full investigation then I was documenting my findings in [this issue](https://github.com/shouldly/shouldly/issues/524) as I was going.

**Comment by JosephWoodward** [comment] 2018-11-06 22:09
@ppumkin I've just [released version 3.0.2](https://www.nuget.org/packages/Shouldly/3.0.2) which should solve this issue, so feel free to give it a try. Thanks for raising this!

**Comment by ppumkin** [comment] 2018-11-07 16:08
@JosephWoodward  Yes it works now. Thank you! 👍

**Comment by JosephWoodward** [comment] 2018-11-07 17:15
@ppumkin Great :D Thanks for reporting it, and thanks for the patience.
